version: '3.9'

services:
  bookshop-app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        uname: ${APP_UNAME}
        uid: ${APP_UID}
        gid: ${APP_GID}
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
    image: bookshop-app/php
    container_name: bookshop-app
    volumes:
      - ./app:/data/bookshop-app
      - ./elastic-data:/data/bookshop-app/elastic-data
    environment:
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      - bookshop-network

  bookshop-elastic:
    container_name: bookshop-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./docker/volumes/es-data:/usr/share/elasticsearch/data
      - ./docker/volumes/es-logs:/usr/share/elasticsearch/logs
    networks:
      - bookshop-network
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - ${ES_PORT}:9200

  bookshop-kibana:
    container_name: bookshop-kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=https://bookshop-elastic:9200
    networks:
      - bookshop-network
    volumes:
      - ./docker/volumes/kibana:/usr/share/kibana/data
    depends_on:
      - bookshop-elastic
    ports:
      - ${KIBANA_PORT}:5601

networks:
  bookshop-network:
    driver: bridge