# версия синтаксиса
version: '3.7'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #Контейнер с PHP, назовём его app
  app:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
    image: myapp/php
    container_name: app # имя контейнера после запуска
    volumes:
      - ./code:/data/myapp.local
      - sock:/sock
    environment:
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  #контейне с Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    image: myapp/nginx
    container_name: webserver
    # проброс портов
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT_SSL}:443"
    volumes:
      - ./code:/data/myapp.local
      - sock:/sock
    networks:
      - app-network

  # контейнер с MySQL
  # строим на базе стандартного образа
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "${MYSQL_PORT}:3306"
    # описываем, какую БД мы создаём
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  sock: